# Generated by Django 3.2.23 on 2024-02-05 09:36

import crud.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', crud.models.UserManager()),
            ],
        ),
    ]
